const route=require('express').Router()
const passport = require('passport')
const userController=require('../controllers/users_controller')

route.post('/sign-up',userController.signUp)
route.get('/sign-in',userController.signIn)
route.post('/create-session',passport.authenticate('local',{failureRedirect:'/user/sign-in'}),userController.createSession)
route.get('/logout',userController.logout)
route.get('/bands',passport.checkAuthentication, userController.displayBands)
route.get('/new-band',passport.checkAuthentication,userController.newBand)
route.post('/new-band',passport.checkAuthentication,userController.createNewBand)
route.get('/reset-password',userController.resetPassDisplay)
route.get('/send-otp',userController.sendOtp)
route.get('/verify-otp',userController.verifyOtp)
route.get('/change-password',userController.changePasswordDisplay)
route.post('/change-password',userController.changePassword)
route.get('/profile',userController.profileDisplay)
route.post('/update-profile',userController.updateProfile)

module.exports=route